module.exports = {
  INDEX01: '首页',
  INDEX02: '客户列表',
  INDEX03: '登录',
  INDEX04: '机会列表',
  INDEX05: '机会详情',
  INDEX06: '订单列表页',
  INDEX07: '用户管理',
  INDEX08: '角色管理',
  INDEX09: '菜单管理',
  INDEX10: '修改密码',
  INDEX11: '销售线索',
  INDEX12: '产品库',
  INDEX13: '产品列表',
  INDEX14: '产品推荐配置列表页',
  INDEX15: '结佣明细列表',
  INDEX16: '上游到账列表',
  INDEX17: '报单审核',
  INDEX18: '搜索配置页',
  INDEX19: '线索汇总表',
  INDEX20: '注册用户转化表',
  INDEX21: '注册分配更新日志列表页',
  INDEX22: '理财师导入列表',
  INDEX23: '理财师导入更新日志列表页',
  INDEX24: '合同管理',
  APPOINTMENTCHECK: '预约审核列表页',
  AICALLLIST: 'AI通话列表'
}
